### ISSUE TITLE
Question: does this gossip protocol pattern match for a pattern and gossip?

### ISSUE THREAD

**Issue by uguessmyid** [hashicorp/memberlist#101]
I want to know whether the gossip protocol here works the same way like seneca does?
on giving a pattern(keyword) to match, will this match and then gossip and respond back where it found that to perform specific action?

**Comment by slackpad** [comment]
Hi @uguessmyid I'm not familiar with Seneca at all, but we do support matching on events. Please take a look at https://www.serf.io/docs/agent/event-handlers.html and https://www.serf.io/docs/commands/query.html. Hope that helps!
