### ISSUE TITLE
Can you please make a release?

### ISSUE THREAD

**Issue by peterbourgon** [hashicorp/memberlist#110]
Most Go dep management tools, including [dep](https://github.com/golang/dep), will expect to operate on tagged releases. Thank you!

**Comment by peterbourgon** [comment]
Hello, bump! There has been some API churn that went unnoticed by me because there wasn't a release to mark it :( Can you please start tagging semver releases?

**Comment by slackpad** [comment]
Hi @peterbourgon went ahead and tagged https://github.com/hashicorp/memberlist/tree/v0.1.0. There were some big API changes but we tried to make them in a fully backward compatible way - I'd be curious to know where we broke things.
