### ISSUE TITLE
Propagation of bad protocol versions causes split brain

### ISSUE THREAD

**Issue by Aestek** [hashicorp/memberlist#180]
Follow-up on https://github.com/hashicorp/consul/issues/3217 
Fixed by: https://github.com/hashicorp/memberlist/pull/178

When starting up, if an alive message for the current node is received before the memberlist is properly initialized the node broadcasts itself with all versions set to 0, causing split brains.

## Steps
* There is a race between https://github.com/hashicorp/memberlist/blob/master/memberlist.go#L186 and https://github.com/hashicorp/memberlist/blob/master/memberlist.go#L202 we can potentially receive messages before we registered ourselves in the memberlist.
* If we receive an alive message for our node at that time we register ourselves with all protocol versions set to 0 https://github.com/hashicorp/memberlist/blob/master/state.go#L901
* We are not bootstrapping (this message comes from another node) so we broadcast our aliveness https://github.com/hashicorp/memberlist/blob/master/state.go#L969. `refute` populates `Vsn` with 0s and sends it to peers.
* The peers receive a message with a `len(Vsn) > 0` and happily update their memberlist with bad versions.

## Impact
When a node attempts to join, we check all the nodes we have and the ones we received to determine the acceptable versions range. If we have been infected with the "version zero bug", our range will be `min: 1, max: 0` (hence the `[1, 0]` messages in Consul logs). This mean we cannot join or be joined. The cluster then proceeds to slowly fall apart.

**Comment by mkeeler** [comment]
Closing as #178 was merged.
