### ISSUE TITLE
message not broadcasted via QueueBroadcast

### ISSUE THREAD

**Issue by vtolstov** [hashicorp/memberlist#181]
i'm run tcpdump and don't see my messages sended via QueueBroadcast

**Comment by vtolstov** [comment]
How can i debug my issue, if i'm try to broadcast message and it not sended.

**Comment by rboyer** [comment]
Can you share a larger example of how you are invoking `TransmitLimitedQueue` methods like `QueueBroadcast`?  The `TransmitLimitedQueue` is just an in memory datastructure with `QueueBroadcast` putting data into the queue and `GetBroadcasts` being used to remove data from the queue. Other parts of memberlist are used to package these messages up for UDP transmission.

**Comment by vtolstov** [comment]
memberlist used in micro framework, but main parts are easy understand.
please check this https://github.com/unistack-org/go-micro/blob/master/registry/gossip/gossip.go

firstly app run NewRegistry and pass some options, after that memberlist created and also may join if specify other nodes.

My debug says that all in this parts are fine and members joined to the cluster, problem part in Register method in this file - https://github.com/unistack-org/go-micro/blob/master/registry/gossip/gossip.go#L463

my debug says that this https://github.com/unistack-org/go-micro/blob/master/registry/gossip/gossip.go#L494 not work.
I'm try to add channel like ch := make(chan struct{}) and pass it to notify and see that after 5-10 second channel does not closed. And tcpdump does not display that message sended.

Communication between nodes are fine, because push/pull works fine

**Comment by vtolstov** [comment]
and thanks for help

**Comment by vtolstov** [comment]
also my debug says if i start gossip without joining QueueBroadcast not send any messages and it queued, this is right?

**Comment by vtolstov** [comment]
also udp work fine between nodes, also i'm try to run on single node and result is the same

**Comment by rboyer** [comment]
Could you possibly add a unit test to your application that showcases the specific problem? That would help me understand your codebase a bit better.

**Comment by vtolstov** [comment]
While I'm write test case, can you say me why udp messages may not sended by memberlist?

**Comment by vtolstov** [comment]
please, check branch gossip of https://github.com/unistack-org/go-micro
i'm write test for gossip that displays this issue.
test file https://github.com/unistack-org/go-micro/blob/gossip/registry/gossip/gossip_test.go

**Comment by vtolstov** [comment]
hmm.. after i pass different configs to different registers (so different memberlist.Config struct to different memberlist.Create) all works fine...

**Comment by vtolstov** [comment]
after test works fine, i'm not understand why real code does not work with the same host with the same ip addresses to bind and to join =(

**Comment by vtolstov** [comment]
Can you provide some hints how can i add debug to memberlist to understand,why the node that startwd first does not receives delegates that sended via broadcast?
Also does udp packets have checksum zero or calculated?

**Comment by vtolstov** [comment]
I'm try to form real clusrer with the same loopback addresses like in test, and on the same hardware and test works fine,but real app first started services does not receives broadcasts

**Comment by vtolstov** [comment]
As i understand my message sizes is too big,more then mtu

**Comment by vtolstov** [comment]
May be write some len test in broadcast sended code and warn when size is bigger?
