### ISSUE TITLE
README: `make deps` needed?

### ISSUE THREAD

**Issue by JensRantil** [hashicorp/memberlist#182]
The README states

> Run `make deps` to fetch dependencies before building

. At the same time, I notice the project relies on Go modules. AFAIK, `go mod download` is implicitly called when issuing `go` commands. Is executing `make deps` legacy from before `go mod` was introduced? Can it be removed from README (and `Makefile`)?

**Comment by i0rek** [comment]
Good catch, this is no longer necessary.
