### ISSUE TITLE
AliveDelegate#NotifyAlive documenation for NotifyMerge?

### ISSUE THREAD

**Issue by JensRantil** [hashicorp/memberlist#183]
https://godoc.org/github.com/hashicorp/memberlist#AliveDelegate states
```
type AliveDelegate interface {
    // NotifyMerge is invoked when a merge could take place.
    // Provides a list of the nodes known by the peer. If
    // the return value is non-nil, the merge is canceled.
    NotifyAlive(peer *Node) error
}
```
but I believe it should at least start with
```
    // NotifyAlive is invoked ...
```
. Is the function name wrong, or is the entire function not documented correctly?

**Comment by JensRantil** [comment]
To expand on this a little but, I know `golint` would have warned about this. Would it make sense to run that on CI? Let me know if I should create a separate issue for this.

**Comment by costela** [comment]
just an FYI: this issue already has a pretty old PR: #146

**Comment by costela** [comment]
another FYI: looks like #146 got merged :grin: :tada:

**Comment by JensRantil** [comment]
:tada: Sweet!
