### ISSUE TITLE
Documentation: Which Config is recommended for multi AZ?

### ISSUE THREAD

**Issue by JensRantil** [hashicorp/memberlist#185]
I am reading https://godoc.org/github.com/hashicorp/memberlist#DefaultLANConfig and https://godoc.org/github.com/hashicorp/memberlist#DefaultLANConfig. Is anyone of them more preferable for multi availability zone replication? If so, how about adding a sentence about? I can submit a PR if you'd like me to.

**Comment by i0rek** [comment]
I don't know what the recommended configuration is, but you could check https://github.com/hashicorp/consul. Consul's server wan is multi dc.

**Comment by JensRantil** [comment]
Excellent. Thanks!
