### ISSUE TITLE
[ask] How do I set handler for received user message?

### ISSUE THREAD

**Issue by beenotung** [hashicorp/memberlist#208]
I don't find a way to set handler on user message. Checked the document and source code, don't see a suitable public method I can call.

I can send user message via `SentTo`, `SendToUDP`, `SendToTCP`, `SendBestEffort`, and `SendReliable` but I don't find a way to set handler for them, expecting something like `SetUserMessageHandler`

**Comment by jon-whit** [comment]
Is there any plan to support something like this? I'm looking for this functionality as well.

**Comment by dnephin** [comment]
I believe what you are looking for is `Delegate.NotifyMsg` (https://pkg.go.dev/github.com/hashicorp/memberlist#Delegate), which can be passed as part of `Config`.

**Comment by beenotung** [comment]
The link shared from dnephin seems solved the question. Thanks
