### ISSUE TITLE
More user-friendly error message for connectivity issues

### ISSUE THREAD

**Issue by krastin** [hashicorp/memberlist#234]
Hello,

After a couple of cases where end-users were perplexed by the following error message, I thought it might be better to state that we were able to connect over TCP explicitly, instead of referring to just 'connection', so that we can make the customer's troubleshooting easier?

https://github.com/hashicorp/memberlist/blob/a43ca4a5f16cd26cbf7b27eb613982bfd09c1753/state.go#L472

Something in the lines of "memberlist: Was able to establish TCP session to %s but other UDP probes failed"? Would that make sense? It will certainly help the user to know what exactly to follow-up on.

Thanks,
Krastin

**Comment by acnodal-tc** [comment]
The https://gitlab.com/purelb/purelb project uses memberlist and one of our users is seeing this message. Do you have any advice on how to debug the cause of it? It sounds like this message indicates that UDP packets from one node to another are being dropped? Is this correct?

**Comment by krastin** [comment]
As far as I understand the code myself, you are correct
