### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by buggyhunter** [hashicorp/memberlist#265]
@krastin is there any plan to release a new version?
latest commits include more detailed error logs.

**Comment by krastin** [comment]
Hi @buggyhunter, unfortunately I'm not the one in charge of releases. I see @kisunji made the last release, perhaps they would know more?

**Comment by kisunji** [comment]
Just published [v0.3.2](https://github.com/hashicorp/memberlist/releases/tag/v0.3.2)
