### ISSUE TITLE
Calling Leave removes the local node from it's own list

### ISSUE THREAD

**Issue by StabbyCutyou** [hashicorp/memberlist#38]
This may or may not be intended behavior - if so, I'd appreciate guidance on the right way to do this.

When calling Leave, the current is marked "dead" and broadcast to the rest of the cluster, while keeping our current listeners still active, so that we can receive updates but not be considered "alive". This helps the cluster heal more rapidly once we re-join.

That makes sense, but I'm having a different use case for Leave, which is not working as intended.

I'd like to be able to tell a node "Hey, leave the cluster and go back to just being on your own - Return to your initial state of a membership of 1". This does not seem to be supported by Leave.

Is there another method that I'm missing here? Is my only option to teardown and re-create a memberlist object from scratch in this case? It would seem like it should be possible to complete cause a natural, and expected, full excision of a given node from a cluster, leaving it in a working state as it would have been before being joined.

Any help would be appreciated

**Comment by armon** [comment]
@StabbyCutyou The simplest way is really to just do the Leave+Shutdown and then create a new memberlist object from there. The internals are not currently designed to handle this use case cleanly

**Comment by StabbyCutyou** [comment]
I figured that was a viable option. Do you think it's more work than worth it to try and make this an "internal" operation? 

I'm willing to spend a little time on it, but if you think it's much more trouble than it's worth, a simple read-lock around using memberlist and teardown/recreate is good enough for my needs.

**Comment by armon** [comment]
My guess is it will be more trouble, as there is just a lot of places you'd need to touch things likely.

**Comment by StabbyCutyou** [comment]
Sounds good - will close

Thanks
