### ISSUE TITLE
IPv6 parsing in resolveAddr doesn't handle the case where the port is missing

### ISSUE THREAD

**Issue by slackpad** [hashicorp/memberlist#63]
This came out of https://github.com/hashicorp/serf/issues/286 but the problem is down in memberlist. Behavior may have varied across Go versions, but with 1.5.2 if you don't supply a port number then it will try to lookup the address via DNS. Adding the port number does the right thing.

We should fix the support for IPV6 addresses without port numbers in`resolveAddr()`.

**Comment by meyskens** [comment]
I was looking into https://github.com/moby/moby/issues/33398 which seems to be an issue in memberlist rather than moby. Seeing the PR is this fixed or not?

**Comment by slackpad** [comment]
Hi @meyskens this should have been closed with #69. Thanks for adding the additional test!
