### ISSUE TITLE
Use of ChannelEventDelegate is not clear

### ISSUE THREAD

**Issue by fithisux** [hashicorp/memberlist#66]
I want to use it as an Events field of a default config. But in my application I cannot read events from the send only channel Ch.

What is the intended purpose?

**Comment by fithisux** [comment]
I believe it is for there for type safety.

Is this the intended usage?

`c := memberlist.DefaultLocalConfig()
observer := new(memberlist.ChannelEventDelegate)
Ch := make(chan memberlist.NodeEvent)
observer.Ch = Ch
c.Events = observer`

**Comment by slackpad** [comment]
Hi @fithisux sorry I missed this one. Your example looks good - there's actually some implementation in event_delgate.go for the channel event delegate that takes the normal `EventDelegate` interface and plumbs that information into the channel.

**Comment by fithisux** [comment]
Hi, I will take a look. Thanks.

On Fri, Mar 18, 2016 at 11:43 PM, James Phillips <notifications@github.com>
wrote:

> Hi @fithisux <https://github.com/fithisux> sorry I missed this one. Your
> example looks good - there's actually some implementation in
> event_delgate.go for the channel event delegate that takes the normal
> EventDelegate interface and plumbs that information into the channel.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/hashicorp/memberlist/issues/66#issuecomment-198556135>
>



-- 
Dr. Vasileios Anagnostopoulos (MSc,PhD)
Researcher/Developer
ICCS/NTUA 9 Heroon Polytechneiou Str., Zografou 15773 Athens,Greece
T (+30) 2107723404 M (+30) 6936935388
E vanag@mail.ntua.gr<mailto:vanag@mail.ntua.gr> www.ntua.gr<
http://www.ntua.gr/>

**Comment by tonglil** [comment]
An example would really help with using the delegates!
