### ISSUE TITLE
Perform on-join DNS requests over TCP

### ISSUE THREAD

**Issue by slackpad** [hashicorp/memberlist#74]
If we make the request via TCP we can more easily get a larger initial join list from the DNS server. Right now the default UDP client will only get a short list of responses (~3). If we pull SRV records we can get the port information as well.

**Comment by armon** [comment]
Agreed :+1:

**Comment by slackpad** [comment]
Looking at https://golang.org/src/net/dnsclient_unix.go#L162, Go's built-in DNS client already does the right thing and asks over TCP if the UDP response is truncated. I'll do a little extra sanity checking but I think we might be done here! Adding SRV support would be a nice addition.

**Comment by slackpad** [comment]
Confirmed the behavior, if you set up the Consul agent to report truncation properly then the Go DNS client will use TCP and pull the full list:

```
{
        "dns_config": {
                "enable_truncate": true
        }
}
```

This kind of sucks though because we only really want this behavior for joining, it's not good in general to turn on truncation, especially with Consul's DNS where you only care about the first few because they are shuffled.

**Comment by slackpad** [comment]
Got a PR up for review. I decided against doing a SRV lookup because there's some ambiguity about port numbers because we have multiple gossip pools so this could lead to some confusion about which one we want to connect to. This keeps the current behavior of using the port if supplied, but otherwise using the configured port.
