### ISSUE TITLE
TestMemberList_ResolveAddr_TCP_First fail

### ISSUE THREAD

**Issue by saturatedfat** [hashicorp/memberlist#90]
Line 421 in memberlist_test.go
change to: ipPort{net.ParseIP("127.0.0.1").To4()
Then run test again

**Comment by slackpad** [comment]
I think this is an artifact of different Go versions. We added this but I removed it in https://github.com/hashicorp/memberlist/commit/591e85c5f6294dd501ac92e2fea0ffc86a447a8e since it broke on Go 1.7.5 (may have broken earlier but this was the first version I noticed it revert).
