### ISSUE TITLE
Question about broadcasts

### ISSUE THREAD

**Issue by F21** [hashicorp/memberlist#92]
I have read https://github.com/hashicorp/memberlist/issues/10 and have the following questions:

1. If I use `QueueBroadcast()` on a `memberlist.TransmitLimitedQueue`, will it send the messages to every single node on the network? If so, why does serf's implementation rebroadcast the message after calling `handleUserEvent()`: https://github.com/hashicorp/serf/blob/555e0dcbb180ecbd03431adc28226bb3192558bc/serf/delegate.go#L62 ?

2. Under what circumstances will a message be broadcast? I am trying to broadcast a protobuf message that's 18 bytes, however, a lot of times, the message does not seem to be broadcast after it is queued.

**Comment by slackpad** [comment]
Hi @F21 for the first question, that queue still relies on gossip to broadcast the message, so a given node won't send it to every node in the cluster - it'll be broadcast via gossip to a few other nodes up to the calculated `retransmitLimit` (from the originating node). The call in `handleUserEvent()` helps keep the even propagating via gossip when it is received on another node. If the event is new to a given node, it'll broadcast it in a similar fashion. This keeps it moving through gossip as long as nodes are still hearing about it for the first time. Hope that helps answer the second question as well!
